name: Flutter CD for Google Play

# This workflow is triggered on pushes to the repository.

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update version in YAML
        run: sed -i 's/99.99.99+99/${{ github.ref_name }}+${{ github.run_number }}/g' pubspec.yaml
      - name: Update version in local.properties
        run:
          |
          sed -i 's/#{APP_VERSION_NAME}#/${{ github.ref_name }}/g' android/key.properties
          sed -i 's/#{APP_VERSION_CODE}#/${{ github.run_number }}/g' android/key.properties
      - name: Update KeyStore password in gradle properties
        run: sed -i 's/#{KEYSTORE_PASS}#/${{ secrets.KEYSTORE_PASS }}/g' android/key.properties
      - name: Update KeyStore key password in gradle properties
        run: sed -i 's/#{KEYSTORE_KEY_PASS}#/${{ secrets.KEYSTORE_KEY_PASS }}/g' android/key.properties
      - name: Update KeyStore alias in gradle properties
        run: sed -i 's/#{KEYSTORE_KEY_ALIAS}#/${{ secrets.KEYSTORE_KEY_ALIAS }}/g' android/key.properties

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          architecture: x64

      - run: flutter pub get
      - run: flutter test --no-sound-null-safety --update-goldens
#      - run: flutter build apk --release --split-per-abi -t lib/main_production.dart
      - run: flutter build appbundle -t lib/main_production.dart
      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  release:
    name: Release app to internal track
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get appbundle from artifacts
        uses: actions/download-artifact@v2
        with:
          name: appbundle
      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.anggach.flutter_clean_arch
          releaseFile: app-release.aab
          track: internal